### ISSUE TITLE
Python Version

### ISSUE THREAD

**Issue by cdbullard** [webis-de/emnlp21-same-sentiment#1]
Hello,

During installation of the required dependencies I noticed that gensim is currently incompatible with Python versions after 3.8 (view the "Code Dependencies" section on [their site](https://radimrehurek.com/gensim/)). Attempting to install gensim on the latest version of Python 3 results in a fatal error; I would recommend updating the README's instructions for the conda environment creation to:

```
conda create -n samesentiment -y python=3.8
```

**Comment by Querela** [comment]
Thank you. I will do so.

I will look at the experimental setup and add the versions of all the dependencies we used. This should also help.

**Comment by cdbullard** [comment]
Thank you for the quick response! 👍

**Comment by Querela** [comment]
Sorry, I was a bit busy but I found time and my environment file. This should help in case some versions do not work anymore. Since it contains a lot of other dependencies due to testing, I still suggest using the instructions in the [README](https://github.com/webis-de/emnlp21-same-sentiment/blob/main/code/README.md) file.

[environment.yml.txt](https://github.com/webis-de/emnlp21-same-sentiment/files/8610436/environment.yml.txt)
